// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pricing/pricing.proto

package pricing

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pricing struct {
	Currency             []*Currency `protobuf:"bytes,1,rep,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Pricing) Reset()         { *m = Pricing{} }
func (m *Pricing) String() string { return proto.CompactTextString(m) }
func (*Pricing) ProtoMessage()    {}
func (*Pricing) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff398099e3bae83b, []int{0}
}

func (m *Pricing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pricing.Unmarshal(m, b)
}
func (m *Pricing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pricing.Marshal(b, m, deterministic)
}
func (m *Pricing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pricing.Merge(m, src)
}
func (m *Pricing) XXX_Size() int {
	return xxx_messageInfo_Pricing.Size(m)
}
func (m *Pricing) XXX_DiscardUnknown() {
	xxx_messageInfo_Pricing.DiscardUnknown(m)
}

var xxx_messageInfo_Pricing proto.InternalMessageInfo

func (m *Pricing) GetCurrency() []*Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

type Currency struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	CmcRank              string   `protobuf:"bytes,4,opt,name=cmc_rank,json=cmcRank,proto3" json:"cmc_rank,omitempty"`
	Quote                *Quote   `protobuf:"bytes,5,opt,name=quote,proto3" json:"quote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Currency) Reset()         { *m = Currency{} }
func (m *Currency) String() string { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()    {}
func (*Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff398099e3bae83b, []int{1}
}

func (m *Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Currency.Unmarshal(m, b)
}
func (m *Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Currency.Marshal(b, m, deterministic)
}
func (m *Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Currency.Merge(m, src)
}
func (m *Currency) XXX_Size() int {
	return xxx_messageInfo_Currency.Size(m)
}
func (m *Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_Currency proto.InternalMessageInfo

func (m *Currency) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Currency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Currency) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Currency) GetCmcRank() string {
	if m != nil {
		return m.CmcRank
	}
	return ""
}

func (m *Currency) GetQuote() *Quote {
	if m != nil {
		return m.Quote
	}
	return nil
}

type Quote struct {
	Usd                  *USD     `protobuf:"bytes,1,opt,name=usd,proto3" json:"usd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quote) Reset()         { *m = Quote{} }
func (m *Quote) String() string { return proto.CompactTextString(m) }
func (*Quote) ProtoMessage()    {}
func (*Quote) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff398099e3bae83b, []int{2}
}

func (m *Quote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quote.Unmarshal(m, b)
}
func (m *Quote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quote.Marshal(b, m, deterministic)
}
func (m *Quote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quote.Merge(m, src)
}
func (m *Quote) XXX_Size() int {
	return xxx_messageInfo_Quote.Size(m)
}
func (m *Quote) XXX_DiscardUnknown() {
	xxx_messageInfo_Quote.DiscardUnknown(m)
}

var xxx_messageInfo_Quote proto.InternalMessageInfo

func (m *Quote) GetUsd() *USD {
	if m != nil {
		return m.Usd
	}
	return nil
}

type USD struct {
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *USD) Reset()         { *m = USD{} }
func (m *USD) String() string { return proto.CompactTextString(m) }
func (*USD) ProtoMessage()    {}
func (*USD) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff398099e3bae83b, []int{3}
}

func (m *USD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_USD.Unmarshal(m, b)
}
func (m *USD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_USD.Marshal(b, m, deterministic)
}
func (m *USD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_USD.Merge(m, src)
}
func (m *USD) XXX_Size() int {
	return xxx_messageInfo_USD.Size(m)
}
func (m *USD) XXX_DiscardUnknown() {
	xxx_messageInfo_USD.DiscardUnknown(m)
}

var xxx_messageInfo_USD proto.InternalMessageInfo

func (m *USD) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Response struct {
	Pricing              *Pricing `protobuf:"bytes,1,opt,name=pricing,proto3" json:"pricing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff398099e3bae83b, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPricing() *Pricing {
	if m != nil {
		return m.Pricing
	}
	return nil
}

func init() {
	proto.RegisterType((*Pricing)(nil), "pricing.Pricing")
	proto.RegisterType((*Currency)(nil), "pricing.Currency")
	proto.RegisterType((*Quote)(nil), "pricing.Quote")
	proto.RegisterType((*USD)(nil), "pricing.USD")
	proto.RegisterType((*Response)(nil), "pricing.Response")
}

func init() { proto.RegisterFile("proto/pricing/pricing.proto", fileDescriptor_ff398099e3bae83b) }

var fileDescriptor_ff398099e3bae83b = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xdf, 0x4b, 0xfb, 0x30,
	0x10, 0xff, 0x66, 0x5d, 0xb7, 0x7e, 0xaf, 0x52, 0xf4, 0x10, 0x89, 0x0e, 0xa4, 0x04, 0xc1, 0x22,
	0x38, 0xa1, 0x03, 0xf1, 0xdd, 0x89, 0xaf, 0x9a, 0xb2, 0x67, 0xe9, 0xb2, 0x20, 0x65, 0x36, 0xad,
	0x69, 0x2b, 0xec, 0x2f, 0xf0, 0xdf, 0x96, 0xa6, 0x49, 0x7d, 0xf0, 0x29, 0xf7, 0xf9, 0x71, 0x97,
	0xe3, 0x73, 0xb0, 0xa8, 0x75, 0xd5, 0x56, 0x77, 0xb5, 0x2e, 0x44, 0xa1, 0xde, 0xdd, 0xbb, 0x34,
	0x2c, 0xce, 0x2d, 0x64, 0x0f, 0x30, 0x7f, 0x19, 0x4a, 0xbc, 0x85, 0x40, 0x74, 0x5a, 0x4b, 0x25,
	0x0e, 0x94, 0xc4, 0x5e, 0x12, 0xa6, 0x27, 0x4b, 0xd7, 0xf5, 0x68, 0x05, 0x3e, 0x5a, 0xd8, 0x37,
	0x81, 0xc0, 0xd1, 0x18, 0xc1, 0xa4, 0xd8, 0x51, 0x12, 0x93, 0xe4, 0x3f, 0x9f, 0x14, 0x3b, 0x44,
	0x98, 0xaa, 0xbc, 0x94, 0x74, 0x62, 0x18, 0x53, 0xe3, 0x19, 0xcc, 0x9a, 0x43, 0xb9, 0xad, 0x3e,
	0xa8, 0x67, 0x58, 0x8b, 0xf0, 0x1c, 0x02, 0x51, 0x8a, 0x37, 0x9d, 0xab, 0x3d, 0x9d, 0x1a, 0x65,
	0x2e, 0x4a, 0xc1, 0x73, 0xb5, 0xc7, 0x2b, 0xf0, 0x3f, 0xbb, 0xaa, 0x95, 0xd4, 0x8f, 0x49, 0x12,
	0xa6, 0xd1, 0xb8, 0xcf, 0x6b, 0xcf, 0xf2, 0x41, 0x64, 0xd7, 0xe0, 0x1b, 0x8c, 0x97, 0xe0, 0x75,
	0xcd, 0xb0, 0x46, 0x98, 0x1e, 0x8d, 0xe6, 0x4d, 0xb6, 0xe6, 0xbd, 0xc0, 0x16, 0xe0, 0x6d, 0xb2,
	0x35, 0x9e, 0x82, 0xdf, 0x4b, 0xd2, 0x18, 0x09, 0x1f, 0x00, 0xbb, 0x87, 0x80, 0xcb, 0xa6, 0xae,
	0x54, 0x23, 0xf1, 0x06, 0x5c, 0x40, 0x76, 0xd8, 0xf1, 0x38, 0xcc, 0xa6, 0xc5, 0x9d, 0x21, 0x7d,
	0x82, 0xc8, 0x72, 0x99, 0xd4, 0x5f, 0x85, 0x90, 0xb8, 0x02, 0x78, 0x96, 0xad, 0x8b, 0xf5, 0x4f,
	0xeb, 0xc5, 0x6f, 0xac, 0xee, 0x43, 0xf6, 0x6f, 0x3b, 0x33, 0x87, 0x59, 0xfd, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x02, 0x92, 0xad, 0x10, 0xb7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PricingServiceClient is the client API for PricingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PricingServiceClient interface {
	GetPricing(ctx context.Context, in *Pricing, opts ...grpc.CallOption) (*Response, error)
}

type pricingServiceClient struct {
	cc *grpc.ClientConn
}

func NewPricingServiceClient(cc *grpc.ClientConn) PricingServiceClient {
	return &pricingServiceClient{cc}
}

func (c *pricingServiceClient) GetPricing(ctx context.Context, in *Pricing, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pricing.PricingService/GetPricing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricingServiceServer is the server API for PricingService service.
type PricingServiceServer interface {
	GetPricing(context.Context, *Pricing) (*Response, error)
}

// UnimplementedPricingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPricingServiceServer struct {
}

func (*UnimplementedPricingServiceServer) GetPricing(ctx context.Context, req *Pricing) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPricing not implemented")
}

func RegisterPricingServiceServer(s *grpc.Server, srv PricingServiceServer) {
	s.RegisterService(&_PricingService_serviceDesc, srv)
}

func _PricingService_GetPricing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pricing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).GetPricing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pricing.PricingService/GetPricing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).GetPricing(ctx, req.(*Pricing))
	}
	return interceptor(ctx, in, info, handler)
}

var _PricingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pricing.PricingService",
	HandlerType: (*PricingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPricing",
			Handler:    _PricingService_GetPricing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pricing/pricing.proto",
}
